config/routes.rb
Rails.application.routes.draw do
  resources :genre_languages

end

app/models/genre_language.rb
class GenreLanguage < ActiveRecord::Base
   validates_uniqueness_of :name
   validates_presence_of :name ,message: "Please add value to Language"
   validates_length_of :name, maximum: 30, message: "less than 30 characters please"
  #validates_format_of :name, :with => /\^[a-zA-Z]+\$/
  validates :name, format: {with: /\A[a-zA-Z_ \-]*\z/}#, message: "only allow characters"
  auto_strip_attributes :name, :squish => true, :nullify => false

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/genre_languages_controller.rb
class GenreLanguagesController < ApplicationController
  before_filter :load


  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found
  def record_not_found
    flash[:notice]= "Record not found"

    render :action => "index"


  end

  def load
    @langs = GenreLanguage.order('name asc')
    @langc = GenreLanguage.count
  end


  def index

    @lang = GenreLanguage.new
  end

  def new
    @lang = GenreLanguage.new
  end

  def create
    @lang = GenreLanguage.new(langParams)
    @lang.save


  end

  def edit

    @lang = GenreLanguage.where(:id =>params[:id])
    #    redirect_to genre_languages_url
    render :action => "index"

  end
  def update
    @lang = GenreLanguage.find(params[:id])

    @lang.update(langParams)

    flash[:notice]="Updated successfully"
    render :action => "index"
    #redirect_to genre_languages_url
  end
  def destroy
    @lang = GenreLanguage.find(params[:id])
    @lang.destroy
    redirect_to genre_languages_url
  end

  def show
    redirect_to genre_language_url
  end

  def langParams
    params.require(:genre_language).permit(:name)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genre_languages_helper.rb
module GenreLanguagesHelper
end

app/views/genre_languages/_form.html.erb
<h1> Genre Language Type</h1>
<%= flash[:notice]%>
<%= flash[:error]%>
<div id ="LanguageType">
  <div>

  </div>

  <%= raise %>
  <%= simple_form_for(@lang) do |f| %>

    <%= f.text_field :name, label: "Genre Language Type", autofocus: true, placeholder: "Enter genre"%>
    <%= f.submit %>
<% end  %>

</div>

app/views/genre_languages/delete.html.erb
<h1>GenreLanguages#delete</h1>
<p>Find me in app/views/genre_languages/delete.html.erb</p>

app/views/genre_languages/edit.html.erb
<%= render 'form' %>

app/views/genre_languages/index.html.erb
<div>
<%= render 'form' %>
</div><br>
<label> Total Records : </label><%= @langc %><br>
<div id="index">
  <table border =1>
    <tr>
      <th>ID      </th>
      <th>Genre Language</th>
    </tr>

  <%  @langs.each do |l| %>
      <tr>
        <td>  <%=        l.id     %>   </td>
        <td>  <%=        l.name        %></td>
        <td><%#= link_to 'show', genre_language_path(l) %></td>
        <td><%= link_to 'Edit', edit_genre_language_path(l) %></td>
        <td><%= link_to 'delete' , genre_language_path(l), method: :delete, message: "Do you want to delete?" %></td>
      </tr>
  <% end  %>
  </table>
  <br>
  <div><%= link_to 'New', new_genre_language_path %></div>
</div>

app/views/genre_languages/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>